export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PATIENTS: '/patients',
  PROTOCOLS: '/protocols',
  PROTOCOL_NUTRITION: '/protocols/:protocolId/nutrition',
  QUESTIONS: '/protocols/questions',
  ARCHIVES: '/archives',
  ALERTS: '/alerts',
  MONITORING: '/monitoring',
  RECOVERY: '/recovery',
  ANALYTICS: '/analytics',
  EXPORT: '/export',
  NOTIFICATIONS: '/notifications',
  STAFF: '/staff',
  NURSES: '/nurses',
  LOGS: '/logs',
  SETTINGS: '/settings',
} as const
