name: Nginx Workflow
description: Workflow to manage Nginx configuration and deployment

on:
  push:
    branches:
      - 'SEP490-*'
      - main
    paths:
      - 'nginx/**'

  workflow_dispatch:
    inputs:
      force_deploy_without_merge:
        description: 'Set this to true to FORCE DEPLOY this without having to merge to main'
        type: boolean
        default: false

jobs:
  check_syntax:
    name: Check Nginx Configuration Syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create dummy certificates for syntax check
        run: |
          mkdir -p ${{ github.workspace }}/dummy_certs
          openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
            -keyout ${{ github.workspace }}/dummy_certs/privkey.pem \
            -out ${{ github.workspace }}/dummy_certs/fullchain.pem \
            -subj "/C=VN/ST=Hanoi/L=Hanoi/O=POMS/CN=example.com"

      - name: Check Nginx Syntax
        run: |
          echo "🌐 Initializing Nginx for syntax check..."

          # Mock Nginx for syntax checking
          docker run --rm \
            -v ${{ github.workspace }}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
            -v ${{ github.workspace }}/nginx/templates:/etc/nginx/templates:ro \
            -v ${{ github.workspace }}/dummy_certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro \
            -v ${{ github.workspace }}/dummy_certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro \
            -e DOMAIN_NAME="example.com" \
            nginx:stable-alpine3.23-perl /bin/sh -c "
              mkdir -p /etc/nginx/conf.d

              echo '--------------------------------------------------'
              for template_file in /etc/nginx/templates/*.template; do
                  [ -e \"\$template_file\" ] || continue
                  base_name=\$(basename \"\$template_file\" .template)
                  
                  echo \"👉 Rendering template: \$base_name.template ...\"
                  envsubst '\$DOMAIN_NAME' < \"\$template_file\" > \"/etc/nginx/conf.d/\$base_name\"
              done
              echo '--------------------------------------------------'
              
              echo \"🔍 Validating configuration syntax...\"
              nginx -t
            "

          echo "✅ Nginx configuration syntax is valid!"

  deploy_nginx:
    name: Hot Reload Nginx Configuration
    needs: check_syntax
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      inputs.force_deploy_without_merge == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Compress Nginx configuration directory
        run: |
          tar -czf ../nginx.tar.gz nginx

      - name: Upload Nginx Artifact via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'nginx.tar.gz'
          target: '/var/www/poms-nginx/'

      - name: Extract, Load Certs & Hot Reload Nginx
        uses: appleboy/ssh-action@v1.2.5
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          B64_FULLCHAIN: ${{ secrets.B64_FULLCHAIN }}
          B64_PRIVKEY: ${{ secrets.B64_PRIVKEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOMAIN_NAME,B64_FULLCHAIN,B64_PRIVKEY
          script: |
            docker network create poms-dev || true
            docker network create poms-staging || true
            docker network create poms-prod || true

            TARGET_DIR="/var/www/poms-nginx"
            cd $TARGET_DIR

            echo "📦 Extracting Nginx configuration..."
            tar -xzf nginx.tar.gz --strip-components=1
            rm nginx.tar.gz

            echo "🔐 Loading SSL certificates..."
            mkdir -p certs
            echo -n "$B64_FULLCHAIN" | base64 --decode > certs/fullchain.pem
            echo -n "$B64_PRIVKEY" | base64 --decode > certs/privkey.pem
            chmod 600 certs/fullchain.pem certs/privkey.pem

            if [ -z "$(docker ps -q -f name=poms-nginx)" ]; then
              echo "🚀 Starting new Nginx instance with new configuration..."
              docker compose -f docker-compose.nginx.yml up -d
            else
              echo "🔥 [CI/CD] Live rendering Nginx templates ..."
              docker exec -e DOMAIN_NAME="$DOMAIN_NAME" poms-nginx sh -c "
                  for template_file in /etc/nginx/templates/*.template; do
                    [ -e \"\$template_file\" ] || continue
                    base_name=\$(basename \"\$template_file\" .template)
                    echo \"👉 Processing template inside container: \$base_name.template\"
                    envsubst '\$DOMAIN_NAME' < \"\$template_file\" > \"/etc/nginx/conf.d/\$base_name\"
                  done
                "

              echo "🔄 [CI/CD] Activating Hot Reload ..."
              docker exec poms-nginx nginx -s reload
            fi

            echo "🔍 Checking health..."
            chmod +x ./resources/scripts/check-health.sh
            ./resources/scripts/check-health.sh poms-nginx 10 2
